# Generated by Django 4.2.4 on 2024-07-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_pedido_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
